include classpath("application.conf")

racingmanager {
    profile = "prod"
    mode = "hosted"
    jwt.keys = [
        {
            kid = "default_key"
            algorithm = "RS256"
            secret = "0c584466-0180-4bcb-920e-a9437ceecbd0"
            active = true
        }
    ]
}
