include classpath("application.conf")

racingmanager {
    profile = "prod"
    mode = "hosted"
    jwt.keys = [
        {
            kid = "default_key"
            algorithm = "RS256"
            secret = ${?RACINGMANAGER_JWT_KEYS_SECRET}
            active = true
        }
    ]
}
